/*
	Một số quyền có thể làm
	Quyền kết nối (CONNECT)
	Quyền thực thi (EXECUTE)
	Quyền quản trị (CREATE, ALTER, DROP)
	Quyền truy cập cơ sở dữ liệu (SELECT, INSERT, UPDATE, DELETE)
	Quyền quản lý quyền hạn (GRANT, REVOKE)
	Quyền quản lý chỉ mục (CREATE INDEX, ALTER INDEX, DROP INDEX)
	Quyền sao lưu và phục hồi (BACKUP, RESTORE)
	Quyền quản lý người dùng (CREATE USER, ALTER USER, DROP USER)
	Quyền quản lý chức năng (CREATE FUNCTION, ALTER FUNCTION, DROP FUNCTION)
	Quyền quản lý vai trò (CREATE ROLE, ALTER ROLE, DROP ROLE)
	Quyền quản lý thủ tục lưu trữ (CREATE PROCEDURE, ALTER PROCEDURE, DROP PROCEDURE)
	Quyền quản lý chủ đề (CREATE SCHEMA, ALTER SCHEMA, DROP SCHEMA)
	Quyền quản lý cơ sở dữ liệu (CREATE DATABASE, ALTER DATABASE, DROP DATABASE)
	Quyền quản lý tập tin (CREATE FILE, ALTER FILE, DROP FILE)
	Quyền quản lý bảo mật (CREATE LOGIN, ALTER LOGIN, DROP LOGIN)
	Quyền quản lý khám phá dữ liệu (CREATE ENDPOINT, ALTER ENDPOINT, DROP ENDPOINT)
	Quyền quản lý thông tin (CREATE EVENT SESSION, ALTER EVENT SESSION, DROP EVENT SESSION)
	Quyền sao chép cơ sở dữ liệu (CREATE DATABASE DDL EVENT NOTIFICATION, CREATE DATABASE DDL TRIGGER)
	Quyền quản lý xác thực (CREATE CREDENTIAL, ALTER CREDENTIAL, DROP CREDENTIAL)
	Quyền quản lý bảo mật cấp cao (ALTER ANY LOGIN, ALTER ANY CREDENTIAL, ALTER ANY USER)
	Quyền quản lý cụm (CREATE AGGREGATE, ALTER AGGREGATE, DROP AGGREGATE)
	Quyền quản lý đăng ký (CREATE ASSEMBLY, ALTER ASSEMBLY, DROP ASSEMBLY)
	Quyền quản lý quy trình (CREATE ROUTE, ALTER ROUTE, DROP ROUTE)
	Quyền quản lý bảo mật chứng chỉ (CONTROL CERTIFICATE, VIEW DEFINITION)
	Quyền quản lý dịch vụ (CREATE SERVICE, ALTER SERVICE, DROP SERVICE)
	Quyền quản lý bảo mật khóa (CONTROL SYMMETRIC KEY, CONTROL ASYMMETRIC KEY)
	Quyền quản lý ràng buộc (CREATE CONSTRAINT, ALTER CONSTRAINT, DROP CONSTRAINT)

*/